spring:
  profiles:
    active: ${PROFILE_NAME}

  application:
    name:
      careroot

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

oauth:
  base-url:
    kakao: ${KAKAO_BASE_URL}
  app-id:
    kakao: ${KAKAO_APP_ID}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: readyou
    region:
      static: ap-southeast-2
    stack:
      auto: false

springdoc:
  swagger-ui:
    path: /api/swagger-ui
  api-docs:
    path: /api/swagger-ui.html

coolsms:
  apikey: {COOL_API_KEY}
  apisecret: {COOL_API_SECRET}
  fromnumber: {COOL_FROMNUMBER}

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:D:/IdeaProjects/testdb/careroute'
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

---

spring:
  config:
    activate:
      on-profile: prd

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        id:
          new_generator_mappings: true